import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/global/Header/page";
import Footer from "@/components/global/Footer/page";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900" ],
  subsets: ["latin"],
});

// const Grobold = localFont({ src: "../font/Grobold.ttf" });


export const metadata: Metadata = {
  title: "Shiba Glow",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    // <html lang="en" className={` ${Grobold.className} ${poppins.className}`}>
    <html lang="en" className={`${poppins.className}`}>
      <body>
        <header className="sticky top-0 bg-[#231106] z-30">
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}