import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/global/NavBar/page";
import Footer from "@/components/global/Footer/page";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900" ],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Shiba Glow",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <header className="sticky top-0 bg-[#231106] z-30">
          <NavBar />
        </header>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}